version: '3.9'
services:
  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    restart: always
    env_file:
      - ./backend/.env